eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://registry:8000/eureka/}
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mongo:
      enabled: false


spring:
  boot:
    admin:
      client:
        url: http://admin:8000
        username: admin
        password: admin
        instance:
          serviceBaseUrl: http://localhost:8000
  rabbitmq:
    addresses: amqps://przwenny:tdDUMBA4zm4PMvqGPx18ey9zhcyhQ3DD@lionfish.rmq.cloudamqp.com/przwenny
  sleuth:
    enabled: true
  zipkin:
    baseUrl: http://zipkin-server:9411
    locator:
      discovery:
        enabled: true
    enabled: true

microservices:
  endpoints:
    endpoint:
      resource-service: resource-service

