training-service:
  maximum: Ayan
  minimum: Saha
spring:
  data:
    mongodb:
      uri: mongodb+srv://learningdb:painkiller@learning-docdb.cdgqj.mongodb.net/learningdb?retryWrites=true&w=majority
  http:
    multipart:
      enabled: true
servlet:
  multipart:
    max-file-size: 500KB
    max-request-size: 500KB   

