training-service:
  maximum: Ayan
  minimum: Saha
spring:
  data:
    mongodb:
      #uri: mongodb+srv://learningdb:painkiller@learning-docdb.cdgqj.mongodb.net/learningdb?retryWrites=true&w=majority
      uri: mongodb://root:example@mongo/learningdb?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false&maxPoolSize=50&connectTimeoutMS=2000
  http:
    multipart:
      enabled: true
servlet:
  multipart:
    max-file-size: 500KB
    max-request-size: 500KB   

